function define(name, value) {
    Object.defineProperty(exports, name, {
        value:      value,
        enumerable: true
    });
}

var white_map={
    "ranchfacebook":1,
    "pigorkut":1,
    "farmorkut_en":1,
    "farmfacebook_ml":1,
    "farmsonico_1":1,
    "farmfacebook_Arab":1,
    "farmmeinvz":1,
    "myislandmeinvz":1,
    "farmfacebook_de":1,
    "farmhyves_1":1,
    "pigmeinvz":1,
    "farmfacebook_pt":1,
    "mhd":1,
    "farmnk":1,
    "hospital_meinvz":1,
    "football_orkut":1,
    "dzpk_orkut":1,
    "dzpk_english":1,
    "dzpk_fanti":1,
    "farm_facebook_tw":1,
    "farmfacebook_tr":1,
    "farm3_meinvz":1,
    "football_meinvz":1,
    "mhc_meinvz":1,
    "mdxd_meinvz":1,
    "kldz_meinvz":1,
    "farmlokalisten":1,
    "hospital_orkut":1,
    "farm3_facebook_de":1,
    "football_facebook_de":1,
    "farm3_facebook_tw_test":1,
    "fish_nk":1,
    "farmfacebook_th_1":1,
    "farmfacebook_th_test":1,
    "dzpk_meinvz":1,
    "casino_meinvz":1,
    "casino_facebook":1,
    "plantmeinvz":1,
    "myisland_lokalisten":1,
    "mhc_lokalisten":1,
    "football_lokalisten":1,
    "pig_lokalisten":1,
    "farm3_lokalisten":1,
    "pandora_test":1,
    "pignl":1,
    "pignk":1,
    "football_orkut_pt":1,
    "hospital_lokalisten":1,
    "mhc_orkut_pt":1,
    "farm3_orkut_pt":1,
    "plant_facebook":1,
    "cafelife_orkut_pt":1,
    "swjy_orkut":1,
    "friendtd":1,
    "cafelife":1,
    "farmfacebook_nl":1,
    "cafelife_meinvz_de":1,
    "mhc_yahoo":1,
    "zooworld":1,
    "magicflower_vz":1,
    "hitower":1,
    "zzzw_orkut_pt":1,
    "elex337":1,
    "ibibo":1,
    "test":1,
    "farmfacebook_arab":1,
    "farmmixi":1,
    "farmzingme":1,
    "qq":1,
    "happyfarm@elex337_en_1.0":1
};

var base_event = {
    'visit':"user.visit",
    'pay':"pay.complete",
    'heartbeat':"user.heartbeat",
    'quit':"user.quit",
    'update':"user.update"};

define("APP_ROOT","d:/work/sender")
define("WHITE_MAP",white_map)
define("BASE_EVENT",base_event)